# INPUTS
# RASTER of HEIGHTS
# BUILDINGS

# OUTPUTS
# BUILDINGS WITH STATS

# PROCESS
OPEN RASTER
GET BOUNDS
OPEN SHAPEFILE USING BOUNDS
CLIP USING BOUNDS
RASTERISE CLIP
SAVE CLIP RASTER

# ZONAL STATS
# MAKE STATS DICT
# LOOP THROUGH BOTH RASTERS' WINDOWS AND ADD 